# Generated by Django 4.1.7 on 2023-04-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0002_dishes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='prize',
            field=models.IntegerField(null=True),
        ),
    ]
